MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: True
  FBNET_V2:
    ARCH: "FBNetV3_G_fpn"
    NORM: "naiveSyncBN"
    WIDTH_DIVISOR: 8
  BACKBONE:
    NAME: FBNetV2FpnBackbone
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: [trunk1, trunk2, trunk3, trunk4]
    NORM: "naiveSyncBN"
    OUT_CHANNELS: 128  # NOTE: reduce from default 256 channels
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    HEAD_NAME: FBNetV2RpnHead
    IN_FEATURES: [p2, p3, p4, p5, p6]
    # Default values are 12000/2000 for train and 6000/1000 for test. In FBNet
    # we use smaller numbers.  TODO: reduce proposals for test in .yaml directly.
    PRE_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: StandardROIHeads
    IN_FEATURES: [p3, p4, p5, p6]
  ROI_BOX_HEAD:
    NAME: FBNetV2RoIBoxHead
    POOLER_RESOLUTION: 6
    NORM: "naiveSyncBN"
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    NORM: "naiveSyncBN"
MODEL_EMA:
  ENABLED: True
  DECAY: 0.9998
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.16
  STEPS: (60000, 80000)
  MAX_ITER: 450000
  LR_SCHEDULER_NAME: WarmupCosineLR
TEST:
  EVAL_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
