name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"  # @daily

jobs:
  python-unittest-cpu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Set up Python
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.8

      - name: Install PyTorch
        run: |
          conda install pytorch torchvision -c pytorch-nightly
          wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
          python collect_env.py

      - name: Install Dependencies
        run: |
          pip install git+https://github.com/facebookresearch/detectron2.git
          pip install git+https://github.com/facebookresearch/mobile-vision
          pip install scikit-learn
          pip install pytest nbval
          pip install -e .

      - name: Run pytest
        run: |
          python -m unittest discover -v -s tests

      - name: Test Notebooks
        run: |
          find . -name *.ipynb | CI=true xargs pytest --nbval-lax --current-env
